[package]
name = "FinalProject"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_code"  # Must match Python import name
crate-type = ["cdylib"]    # Required for Python extensions

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }  # For Python bindings
rayon = "1.8"  # For parallel processing